name: 'Allure Report with history'
description: 'Generate Allure Report with history'
author: 'simple-elf'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  allure_report:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  allure_history:
    description: 'Folder for allure history'
    required: true
    default: 'allure-history'
  subfolder:
    description: 'subfolder'
    required: false
    default: ''
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  github_repo:
    description: 'GitHub repository'
    required: true
    default: ${{ github.repository }}
  github_repo_owner:
    description: 'GitHub repository owner'
    required: true
    default: ${{ github.repository_owner }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
  github_server_url:
    description: 'GitHub server URL'
    required: true
    default: ${{ github.server_url }}
  allure_release:
    description: 'Allure release'
    required: false
    default: '2.27.0'
  allure_repo:
    description: 'Allure repo'
    required: false
    default: 'https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline'
runs:
  using: composite
  steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    
    - name: Download allure cli
      shell: bash
      run: |
        wget --no-verbose -O /tmp/allure-${{ inputs.allure_release }}.tgz ${{ inputs.allure_repo }}/${{ inputs.allure_release }}/allure-commandline-${{ inputs.allure_release }}.tgz
        tar -xf /tmp/allure-${{ inputs.allure_release }}.tgz
        chmod -R +x allure-${{ inputs.allure_release }}/bin
        echo allure-${{ inputs.allure_release }}/bin >> $GITHUB_PATH
      
    - name: Generate report
      shell: bash
      run: |
        echo '{"name":"GitHub Actions","type":"github","reportName":"Allure Report",' > ${{ inputs.allure_results }}/executor.json
        echo "\"url\":\"https://${{ inputs.github_repo_owner }}.github.io/${{ inputs.github_repo }}\"," >> ${{ inputs.allure_results }}/executor.json # ???
        echo "\"reportUrl\":\"https://${{ inputs.github_repo_owner }}.github.io/${{ inputs.github_repo }}/${{ inputs.github_run_num }}/\"," >> ${{ inputs.allure_results }}/executor.json
        echo "\"buildUrl\":\"${{ inputs.github_server_url }}/${{ inputs.github_repo }}/actions/runs/${{ inputs.github_run_id }}\"," >> ${{ inputs.allure_results }}/executor.json
        echo "\"buildName\":\"GitHub Actions Run #${{ inputs.github_run_id }}\",\"buildOrder\":\"${{ inputs.github_run_num }}\"}" >> ${{ inputs.allure_results }}/executor.json
        allure generate --clean ${{ inputs.allure_results }} -o ${{ inputs.allure_report }}
